### ISSUE TITLE
Initialization Problem

### ISSUE THREAD

**Issue by jkugiya** [chaabaj/openid-scala#4]
Using anonymous class and overriding its fields causes complex initialization problem sometimes. (`ActorSysterm` will be null sometimes)

Defining class explicitly is better. As following

```
private class SlackOAuthServiceImpl(
  override val config: OAuthConfig)(implicit actorSystem: ActorSystem, timeout: FiniteDuration) extends SlackOAuthService {
  override val webServiceApi: WebServiceApi[JsValue] = WebServiceApi(new JsonProtocol)
}

object SlackOAuthService {
  def apply(oauthConfig: OAuthConfig)(implicit actorSystem: ActorSystem, timeout: FiniteDuration): OAuthService =
    new SlackOAuthServiceImpl(oauthConfig)
}
```

**Comment by chaabaj** [comment]
Ok i see what you mean, but implicit aren't checked by the compiler?
This is a point i don't understand, What is the difference by create a class explicitly in this case ?
For my point of view, your solution is doing the same except the inheritance and naming the class.
Maybe i misunderstand the problem so could you elaborate more?

**Comment by jkugiya** [comment]
Try following code

```
trait A {
  val value: String
}

object A {
   def apply(): A = new A { val value: String = "test" }
}
trait B {
  println("trait B")
  implicit val a: A
  val v = foo()
  private def foo()(implicit a: A): String = {
     a.value
  }
}
class BImpl()(implicit override val a: A) extends B {
  println("BImpl")
}
object B {
  def apply(): B = new B {
     println("class B")
     implicit val a = A()
  }

  def create(): B = new BImpl()({ println("BImpl constuctor"); A()})
}
```

`B()` will get `NullPointerException`, but `B.create()` will not. Because constuctor sequence is `trait B -> anonymous class B`. But `a` is given at B's constructor when `new BImpl()(A())`. Please confirm console output.

**Comment by jkugiya** [comment]
So `WebServiceApi#request` will get `NullPointerException` because timeout is not given.

**Comment by chaabaj** [comment]
Ok i will try it

**Comment by chaabaj** [comment]
Fixed
